# Generated by Django 5.1.2 on 2024-11-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillfinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Имя'),
        ),
    ]
