# Generated by Django 5.1.2 on 2024-11-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillfinance', '0006_category_entertainment'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
