# Generated by Django 5.1.2 on 2024-11-15 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillfinance', '0007_entertainment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.ForeignKey(blank=True, help_text='Категории пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to='chillfinance.category'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user_bank_account',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='chillfinance.bankaccount'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
