# Generated by Django 5.1.2 on 2024-11-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillfinance', '0008_customuser_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='categories',
        ),
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Категории пользователя', null=True, to='chillfinance.category'),
        ),
    ]
